import type { Job, User, ChatMessage, Notification } from '../types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Full Stack Engineer',
    company: 'Stripe',
    location: 'San Francisco, CA',
    country: 'United States',
    salary: { min: 180000, max: 240000, currency: 'USD', period: 'year' },
    type: 'full-time',
    level: 'senior',
    visaSponsorship: true,
    skills: ['React', 'Node.js', 'TypeScript', 'Go', 'PostgreSQL'],
    description:
      'Join Stripe\'s infrastructure team to build the financial systems that power millions of businesses worldwide. You\'ll work on high-scale distributed systems and collaborate with world-class engineers.',
    requirements: [
      '5+ years of full-stack development experience',
      'Strong knowledge of distributed systems',
      'Experience with React and Node.js',
      'Excellent problem-solving skills',
    ],
    benefits: [
      'H-1B and O-1 visa sponsorship',
      'Relocation assistance',
      'Equity package',
      'Comprehensive health insurance',
      'Remote work options',
      '401(k) matching',
    ],
    postedAt: '2026-04-10T10:00:00Z',
    deadline: '2026-05-10T10:00:00Z',
    applicants: 342,
    category: 'engineering',
    remote: false,
    source: 'Stripe Careers',
    sourceUrl: 'https://stripe.com/jobs',
    aiMatchScore: 96,
    featured: true,
  },
  {
    id: '2',
    title: 'AI/ML Engineer',
    company: 'OpenAI',
    location: 'Remote',
    country: 'United States',
    salary: { min: 200000, max: 300000, currency: 'USD', period: 'year' },
    type: 'full-time',
    level: 'senior',
    visaSponsorship: true,
    skills: ['Python', 'PyTorch', 'TensorFlow', 'CUDA', 'Distributed Training'],
    description:
      'Work at the frontier of AI research and deployment. You\'ll train and fine-tune large language models, optimize inference pipelines, and push the boundaries of what\'s possible with AI.',
    requirements: [
      'PhD or MS in Computer Science, ML, or related field',
      'Experience training large-scale models',
      'Strong Python and PyTorch skills',
      'Publications in top ML venues a plus',
    ],
    benefits: [
      'Full visa sponsorship (H-1B, O-1, EB-1)',
      'Top 1% compensation',
      'Cutting-edge compute access',
      'Mission-driven culture',
    ],
    postedAt: '2026-04-11T08:00:00Z',
    applicants: 1204,
    category: 'data',
    remote: true,
    source: 'OpenAI Careers',
    sourceUrl: 'https://openai.com/careers',
    aiMatchScore: 91,
    featured: true,
  },
  {
    id: '3',
    title: 'Product Designer',
    company: 'Figma',
    location: 'New York, NY',
    country: 'United States',
    salary: { min: 140000, max: 190000, currency: 'USD', period: 'year' },
    type: 'full-time',
    level: 'mid',
    visaSponsorship: true,
    skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
    description:
      'Design the future of collaborative design tools. You\'ll own end-to-end product design for core features used by millions of designers and developers every day.',
    requirements: [
      '4+ years of product design experience',
      'Portfolio showcasing complex product work',
      'Experience with design systems',
      'Strong communication skills',
    ],
    benefits: [
      'Visa sponsorship available',
      'Flexible remote policy',
      'Design tool stipend',
      'Generous equity',
    ],
    postedAt: '2026-04-09T12:00:00Z',
    applicants: 567,
    category: 'design',
    remote: false,
    source: 'Figma Jobs',
    sourceUrl: 'https://figma.com/jobs',
    aiMatchScore: 84,
  },
  {
    id: '4',
    title: 'Data Scientist',
    company: 'Spotify',
    location: 'Stockholm, Sweden',
    country: 'Sweden',
    salary: { min: 75000, max: 110000, currency: 'EUR', period: 'year' },
    type: 'full-time',
    level: 'mid',
    visaSponsorship: true,
    skills: ['Python', 'SQL', 'Spark', 'A/B Testing', 'Statistics'],
    description:
      'Help Spotify understand and serve its 600M+ users better. You\'ll work on recommendation algorithms, user behavior models, and data-driven product decisions.',
    requirements: [
      'MS/PhD in Statistics, Data Science, or related field',
      '3+ years of industry experience',
      'Strong SQL and Python skills',
      'Experience with large-scale data processing',
    ],
    benefits: [
      'EU Blue Card sponsorship',
      'Work permit for non-EU nationals',
      'Relocation package',
      'Premium Spotify subscription',
    ],
    postedAt: '2026-04-08T09:00:00Z',
    applicants: 289,
    category: 'data',
    remote: false,
    source: 'Spotify Careers',
    sourceUrl: 'https://spotify.com/careers',
    aiMatchScore: 88,
  },
  {
    id: '5',
    title: 'Backend Engineer — Payments',
    company: 'Revolut',
    location: 'London, UK',
    country: 'United Kingdom',
    salary: { min: 80000, max: 120000, currency: 'GBP', period: 'year' },
    type: 'full-time',
    level: 'senior',
    visaSponsorship: true,
    skills: ['Kotlin', 'Java', 'Kafka', 'PostgreSQL', 'Microservices'],
    description:
      'Build the next generation of financial infrastructure at one of Europe\'s fastest-growing fintechs. Work on high-throughput payment systems processing billions of transactions.',
    requirements: [
      '4+ years backend engineering experience',
      'Experience with JVM languages (Kotlin/Java)',
      'Knowledge of distributed systems and microservices',
      'Financial domain experience a plus',
    ],
    benefits: [
      'Tier 2 General visa sponsorship (UK)',
      'Stock options',
      'Private health insurance',
      'Flexible working',
    ],
    postedAt: '2026-04-07T14:00:00Z',
    applicants: 445,
    category: 'engineering',
    remote: false,
    source: 'Revolut Jobs',
    sourceUrl: 'https://revolut.com/careers',
    aiMatchScore: 79,
  },
  {
    id: '6',
    title: 'DevOps / Platform Engineer',
    company: 'Shopify',
    location: 'Remote — Worldwide',
    country: 'Canada',
    salary: { min: 130000, max: 180000, currency: 'CAD', period: 'year' },
    type: 'full-time',
    level: 'senior',
    visaSponsorship: true,
    skills: ['Kubernetes', 'Terraform', 'AWS', 'Go', 'Prometheus'],
    description:
      'Help Shopify\'s platform scale to support millions of merchants. You\'ll design and operate the infrastructure that powers global commerce.',
    requirements: [
      '5+ years in DevOps/Platform/SRE role',
      'Deep knowledge of Kubernetes and cloud infrastructure',
      'Experience with Terraform and IaC',
      'Strong scripting skills',
    ],
    benefits: [
      'LMIA-exempt work permit (Canada)',
      'Fully remote',
      'Remote equipment budget',
      'Wellness allowance',
    ],
    postedAt: '2026-04-06T11:00:00Z',
    applicants: 198,
    category: 'engineering',
    remote: true,
    source: 'Shopify Careers',
    sourceUrl: 'https://shopify.com/careers',
    aiMatchScore: 85,
  },
  {
    id: '7',
    title: 'iOS Engineer',
    company: 'Airbnb',
    location: 'San Francisco, CA',
    country: 'United States',
    salary: { min: 170000, max: 230000, currency: 'USD', period: 'year' },
    type: 'full-time',
    level: 'senior',
    visaSponsorship: true,
    skills: ['Swift', 'SwiftUI', 'Objective-C', 'React Native', 'GraphQL'],
    description:
      'Build the Airbnb app used by hundreds of millions of travelers. You\'ll own significant features, mentor engineers, and influence the technical direction of our mobile platform.',
    requirements: [
      '5+ years iOS development experience',
      'Expert knowledge of Swift and SwiftUI',
      'Experience with large-scale iOS apps',
      'Strong computer science fundamentals',
    ],
    benefits: [
      'H-1B visa sponsorship',
      'Travel credits',
      'Equity package',
      'On-site amenities',
    ],
    postedAt: '2026-04-05T10:00:00Z',
    applicants: 521,
    category: 'engineering',
    remote: false,
    source: 'Airbnb Careers',
    sourceUrl: 'https://airbnb.com/careers',
    aiMatchScore: 82,
  },
  {
    id: '8',
    title: 'Growth Marketing Manager',
    company: 'Notion',
    location: 'Remote — US/EU',
    country: 'United States',
    salary: { min: 120000, max: 160000, currency: 'USD', period: 'year' },
    type: 'full-time',
    level: 'mid',
    visaSponsorship: false,
    skills: ['Growth Marketing', 'SEO', 'Paid Acquisition', 'Analytics', 'A/B Testing'],
    description:
      'Drive Notion\'s next phase of growth through data-driven marketing strategies. You\'ll own acquisition channels, run experiments, and grow a global user base.',
    requirements: [
      '4+ years of growth/performance marketing',
      'Experience with paid channels and SEO',
      'Strong analytical mindset',
      'B2B SaaS experience preferred',
    ],
    benefits: [
      'Fully remote',
      'Generous PTO',
      'Home office stipend',
      'Learning budget',
    ],
    postedAt: '2026-04-04T15:00:00Z',
    applicants: 312,
    category: 'marketing',
    remote: true,
    source: 'Notion Jobs',
    sourceUrl: 'https://notion.so/jobs',
    aiMatchScore: 72,
  },
  {
    id: '9',
    title: 'Finance Manager — FP&A',
    company: 'Klarna',
    location: 'Berlin, Germany',
    country: 'Germany',
    salary: { min: 85000, max: 115000, currency: 'EUR', period: 'year' },
    type: 'full-time',
    level: 'mid',
    visaSponsorship: true,
    skills: ['Financial Modeling', 'Excel', 'SQL', 'Business Intelligence', 'FP&A'],
    description:
      'Join Klarna\'s finance team to drive strategic financial planning. You\'ll build models, generate insights, and partner with business leaders to drive growth.',
    requirements: [
      '5+ years in FP&A or corporate finance',
      'Strong financial modeling skills',
      'Experience with BI tools',
      'Fluent English; German a plus',
    ],
    benefits: [
      'EU Blue Card support',
      'Relocation package',
      'Stock options',
      'Flexible working hours',
    ],
    postedAt: '2026-04-03T09:00:00Z',
    applicants: 156,
    category: 'finance',
    remote: false,
    source: 'Klarna Careers',
    sourceUrl: 'https://klarna.com/careers',
    aiMatchScore: 76,
  },
  {
    id: '10',
    title: 'Product Manager — Core Platform',
    company: 'Linear',
    location: 'Remote — Global',
    country: 'United States',
    salary: { min: 160000, max: 200000, currency: 'USD', period: 'year' },
    type: 'full-time',
    level: 'senior',
    visaSponsorship: true,
    skills: ['Product Strategy', 'Roadmapping', 'User Research', 'SQL', 'Agile'],
    description:
      'Define the future of the best issue tracker for software teams. You\'ll work closely with engineering and design to ship impactful features that delight developers worldwide.',
    requirements: [
      '5+ years of product management experience',
      'Track record of shipping excellent developer tools',
      'Strong technical background',
      'Exceptional written communication',
    ],
    benefits: [
      'Visa sponsorship considered',
      'Fully remote',
      'Competitive equity',
      'Home office budget',
    ],
    postedAt: '2026-04-02T10:00:00Z',
    applicants: 234,
    category: 'product',
    remote: true,
    source: 'Linear Jobs',
    sourceUrl: 'https://linear.app/careers',
    aiMatchScore: 90,
  },
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Chen',
  email: 'alex.chen@email.com',
  title: 'Full Stack Engineer',
  skills: ['React', 'TypeScript', 'Node.js', 'Python', 'PostgreSQL'],
  location: 'Bangalore, India',
  visaStatus: 'requires_sponsorship',
  preferredLocations: ['United States', 'United Kingdom', 'Canada', 'Germany'],
  preferredCategories: ['engineering', 'data', 'product'],
  savedJobIds: ['1', '2', '10'],
  appliedJobIds: ['4'],
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'match',
    title: '🎯 96% Match Found!',
    body: 'Stripe is looking for a Senior Full Stack Engineer — perfect for your profile.',
    read: false,
    createdAt: '2026-04-13T09:00:00Z',
    jobId: '1',
  },
  {
    id: 'n2',
    type: 'match',
    title: '🤖 AI Just Found 3 New Jobs',
    body: 'New visa-sponsorship roles in your preferred categories were scraped.',
    read: false,
    createdAt: '2026-04-12T15:30:00Z',
  },
  {
    id: 'n3',
    type: 'deadline',
    title: '⏰ Application Deadline Soon',
    body: 'Stripe Senior Full Stack Engineer closes in 27 days.',
    read: true,
    createdAt: '2026-04-11T10:00:00Z',
    jobId: '1',
  },
  {
    id: 'n4',
    type: 'application',
    title: '📨 Application Sent',
    body: 'Your application to Spotify Data Scientist was submitted.',
    read: true,
    createdAt: '2026-04-10T14:00:00Z',
    jobId: '4',
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'm1',
    role: 'assistant',
    content:
      "Hi! I'm your VisaHire AI assistant 👋\n\nI help you find visa-sponsored jobs, review your profile for job fit, prep for interviews, and more.\n\nWhat can I help you with today?",
    timestamp: '2026-04-13T09:00:00Z',
  },
];

export const JOB_CATEGORIES = [
  { id: 'engineering', label: 'Engineering', icon: '💻' },
  { id: 'design', label: 'Design', icon: '🎨' },
  { id: 'data', label: 'Data & AI', icon: '🤖' },
  { id: 'product', label: 'Product', icon: '📦' },
  { id: 'marketing', label: 'Marketing', icon: '📣' },
  { id: 'finance', label: 'Finance', icon: '💰' },
  { id: 'operations', label: 'Operations', icon: '⚙️' },
  { id: 'sales', label: 'Sales', icon: '🤝' },
  { id: 'healthcare', label: 'Healthcare', icon: '🏥' },
  { id: 'legal', label: 'Legal', icon: '⚖️' },
] as const;

export const TOP_COUNTRIES = [
  { name: 'United States', flag: '🇺🇸', jobs: 4821 },
  { name: 'United Kingdom', flag: '🇬🇧', jobs: 2103 },
  { name: 'Canada', flag: '🇨🇦', jobs: 1834 },
  { name: 'Germany', flag: '🇩🇪', jobs: 1456 },
  { name: 'Netherlands', flag: '🇳🇱', jobs: 987 },
  { name: 'Sweden', flag: '🇸🇪', jobs: 756 },
  { name: 'Australia', flag: '🇦🇺', jobs: 943 },
  { name: 'Singapore', flag: '🇸🇬', jobs: 612 },
];

export const AI_QUICK_PROMPTS = [
  'Find me visa-sponsored React jobs in the US',
  'Review my profile and suggest improvements',
  'Which companies have the best H-1B approval rates?',
  'How do I tailor my resume for tech roles?',
  'What visa options are available in Canada for engineers?',
  'Find remote jobs that sponsor visas worldwide',
];
